version: '3.9'

services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - payment-service
      - notification-service

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "4002:4002"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "4003:4003"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "4004:4004"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "4005:4005"
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
